// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjVjscIkYBgb1Oo_KYyedsC9jIHgTLEaw',
    appId: '1:665357169320:web:228d800b1a3e2befc1c89d',
    messagingSenderId: '665357169320',
    projectId: 'quizzer-e2733',
    authDomain: 'quizzer-e2733.firebaseapp.com',
    storageBucket: 'quizzer-e2733.appspot.com',
    measurementId: 'G-N3FMVCZ7YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt9U33YQdZUPPI-Ruu6Jf9IBgw1WfQeyA',
    appId: '1:665357169320:android:1b60337f3c6ef554c1c89d',
    messagingSenderId: '665357169320',
    projectId: 'quizzer-e2733',
    storageBucket: 'quizzer-e2733.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7HP8gIyunxEltD37lZqmNO3qC7kaewk0',
    appId: '1:665357169320:ios:48a8ae531a20ad3fc1c89d',
    messagingSenderId: '665357169320',
    projectId: 'quizzer-e2733',
    storageBucket: 'quizzer-e2733.appspot.com',
    iosClientId: '665357169320-9j8902ciolgd6ch3618ggsfdsdft547s.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizzer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7HP8gIyunxEltD37lZqmNO3qC7kaewk0',
    appId: '1:665357169320:ios:48a8ae531a20ad3fc1c89d',
    messagingSenderId: '665357169320',
    projectId: 'quizzer-e2733',
    storageBucket: 'quizzer-e2733.appspot.com',
    iosClientId: '665357169320-9j8902ciolgd6ch3618ggsfdsdft547s.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizzer',
  );
}
